type ReadModelTable<
  TName extends string,
  TColumns extends readonly string[],
> = {
  columns: TColumns;
  name: TName;
};

function defineTable<TName extends string, TColumns extends readonly string[]>(
  name: TName,
  columns: TColumns,
): ReadModelTable<TName, TColumns> {
  return {
    columns,
    name,
  };
}

export const YNAB_READ_MODEL_TABLES = {
  syncState: defineTable("ynab_sync_state", [
    "plan_id",
    "endpoint",
    "server_knowledge",
    "last_successful_sync_at",
    "last_failed_sync_at",
    "health_status",
    "last_error",
    "rows_upserted_last_run",
    "rows_deleted_last_run",
    "lease_owner",
    "lease_expires_at",
    "created_at",
    "updated_at",
  ] as const),
  syncRuns: defineTable("ynab_sync_runs", [
    "id",
    "plan_id",
    "endpoint",
    "started_at",
    "finished_at",
    "status",
    "server_knowledge_before",
    "server_knowledge_after",
    "rows_upserted",
    "rows_deleted",
    "error",
  ] as const),
  users: defineTable("ynab_users", [
    "id",
    "name",
    "synced_at",
    "updated_at",
  ] as const),
  plans: defineTable("ynab_plans", [
    "id",
    "name",
    "last_modified_on",
    "first_month",
    "last_month",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  planSettings: defineTable("ynab_plan_settings", [
    "plan_id",
    "date_format",
    "currency_iso_code",
    "currency_example_format",
    "currency_decimal_digits",
    "currency_decimal_separator",
    "currency_symbol_first",
    "currency_group_separator",
    "currency_symbol",
    "currency_display_symbol",
    "synced_at",
    "updated_at",
  ] as const),
  accounts: defineTable("ynab_accounts", [
    "plan_id",
    "id",
    "name",
    "type",
    "on_budget",
    "closed",
    "note",
    "balance_milliunits",
    "cleared_balance_milliunits",
    "uncleared_balance_milliunits",
    "transfer_payee_id",
    "direct_import_linked",
    "direct_import_in_error",
    "last_reconciled_at",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  categoryGroups: defineTable("ynab_category_groups", [
    "plan_id",
    "id",
    "name",
    "hidden",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  categories: defineTable("ynab_categories", [
    "plan_id",
    "id",
    "category_group_id",
    "category_group_name",
    "original_category_group_id",
    "name",
    "note",
    "hidden",
    "budgeted_milliunits",
    "activity_milliunits",
    "balance_milliunits",
    "goal_type",
    "goal_target_milliunits",
    "goal_target_date",
    "goal_target_month",
    "goal_needs_whole_amount",
    "goal_day",
    "goal_cadence",
    "goal_cadence_frequency",
    "goal_creation_month",
    "goal_percentage_complete",
    "goal_months_to_budget",
    "goal_under_funded_milliunits",
    "goal_overall_funded_milliunits",
    "goal_overall_left_milliunits",
    "goal_snoozed_at",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  months: defineTable("ynab_months", [
    "plan_id",
    "month",
    "note",
    "income_milliunits",
    "budgeted_milliunits",
    "activity_milliunits",
    "to_be_budgeted_milliunits",
    "age_of_money",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  monthCategories: defineTable("ynab_month_categories", [
    "plan_id",
    "month",
    "category_id",
    "category_group_id",
    "category_group_name",
    "original_category_group_id",
    "name",
    "note",
    "budgeted_milliunits",
    "activity_milliunits",
    "balance_milliunits",
    "goal_under_funded_milliunits",
    "goal_type",
    "goal_target_milliunits",
    "goal_target_date",
    "goal_target_month",
    "goal_needs_whole_amount",
    "goal_day",
    "goal_cadence",
    "goal_cadence_frequency",
    "goal_creation_month",
    "goal_percentage_complete",
    "goal_months_to_budget",
    "goal_overall_funded_milliunits",
    "goal_overall_left_milliunits",
    "goal_snoozed_at",
    "hidden",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  payees: defineTable("ynab_payees", [
    "plan_id",
    "id",
    "name",
    "transfer_account_id",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  payeeLocations: defineTable("ynab_payee_locations", [
    "plan_id",
    "id",
    "payee_id",
    "latitude",
    "longitude",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  transactions: defineTable("ynab_transactions", [
    "plan_id",
    "id",
    "date",
    "amount_milliunits",
    "memo",
    "cleared",
    "approved",
    "flag_color",
    "flag_name",
    "account_id",
    "account_name",
    "payee_id",
    "payee_name",
    "category_id",
    "category_name",
    "transfer_account_id",
    "transfer_transaction_id",
    "matched_transaction_id",
    "import_id",
    "import_payee_name",
    "import_payee_name_original",
    "debt_transaction_type",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  subtransactions: defineTable("ynab_subtransactions", [
    "plan_id",
    "transaction_id",
    "id",
    "amount_milliunits",
    "memo",
    "payee_id",
    "payee_name",
    "category_id",
    "category_name",
    "transfer_account_id",
    "transfer_transaction_id",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  scheduledTransactions: defineTable("ynab_scheduled_transactions", [
    "plan_id",
    "id",
    "date_first",
    "date_next",
    "frequency",
    "amount_milliunits",
    "memo",
    "flag_color",
    "flag_name",
    "account_id",
    "account_name",
    "payee_id",
    "payee_name",
    "category_id",
    "category_name",
    "transfer_account_id",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  scheduledSubtransactions: defineTable("ynab_scheduled_subtransactions", [
    "plan_id",
    "scheduled_transaction_id",
    "id",
    "amount_milliunits",
    "memo",
    "payee_id",
    "payee_name",
    "category_id",
    "category_name",
    "transfer_account_id",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  moneyMovements: defineTable("ynab_money_movements", [
    "plan_id",
    "id",
    "month",
    "moved_at",
    "note",
    "money_movement_group_id",
    "performed_by_user_id",
    "from_category_id",
    "to_category_id",
    "amount_milliunits",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
  moneyMovementGroups: defineTable("ynab_money_movement_groups", [
    "plan_id",
    "id",
    "group_created_at",
    "month",
    "note",
    "performed_by_user_id",
    "deleted",
    "synced_at",
    "updated_at",
  ] as const),
} as const;

export type YnabReadModelTableKey = keyof typeof YNAB_READ_MODEL_TABLES;
export type YnabReadModelTableName =
  (typeof YNAB_READ_MODEL_TABLES)[YnabReadModelTableKey]["name"];
